branches:
    - master
    - auto
    - try

context: f28-codestyle

required: true
container:
  image: registry.fedoraproject.org/fedora:28

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/codestyle.sh

---

context: f28-primary-1
inherit: true

# https://github.com/ostreedev/ostree/pull/1513#issuecomment-378784162
host:
  distro: fedora/28/atomic
  specs:
    ram: 8192
#container:
#  image: registry.fedoraproject.org/fedora:28

tests:
  - modprobe -r kvm_intel || true
  - modprobe kvm_intel nested=1
  - docker run --device /dev/kvm --rm -v $(pwd):/srv/code:z
    --env VMCHECK_PARALLEL=${VMCHECK_PARALLEL}
    --env TESTS_OFFSET=${TESTS_OFFSET}
    --env TESTS_MODULUS=${TESTS_MODULUS}
    --env CFLAGS="${CFLAGS}" --env ASAN_OPTIONS=${ASAN_OPTIONS}
    registry.fedoraproject.org/fedora:28 /bin/sh -c "cd /srv/code && ./ci/papr-vmcheck.sh"

env:
  # each VM is (currently) 1024MB, so we'll leave 1G for the OS
  VMCHECK_PARALLEL: '5'
  # TODO use -fsanitize=address
  CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -O2 -Wp,-D_FORTIFY_SOURCE=2'
  ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
  TESTS_OFFSET: '0'
  TESTS_MODULUS: '3'

timeout: 60m

artifacts:
  - artifacts/
  - test-suite.log
  - config.log
  - vmcheck

---

context: f28-primary-2
inherit: true

# Copy of above, with modified TESTS_OFFSET
env:
  VMCHECK_PARALLEL: '5'
  CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -O2 -Wp,-D_FORTIFY_SOURCE=2'
  ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
  # This one runs the other half of the tests
  TESTS_OFFSET: '1'
  TESTS_MODULUS: '2'

---

context: f28-primary-3
inherit: true

# Copy of above, with modified TESTS_OFFSET
env:
  VMCHECK_PARALLEL: '5'
  CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -O2 -Wp,-D_FORTIFY_SOURCE=2'
  ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
  # This one runs the other half of the tests
  TESTS_OFFSET: '2'
  TESTS_MODULUS: '3'


---

inherit: true

context: c7-primary

required: true

# FIXME; temporary workaround
# https://github.com/ostreedev/ostree/pull/1513#issuecomment-378784162
host:
  distro: fedora/28/atomic
  specs:
    ram: 4096
#container:
#  image: registry.centos.org/centos/centos:7

# We only want the sanitizers on Fedora
env:
    CFLAGS: ''

tests:
  # If we're still on devmapper, we need to expand rootfs for tests
  - lvresize -r -l +100%FREE atomicos/root
  - docker run --device /dev/kvm --rm -v $(pwd):/srv/code:z registry.centos.org/centos/centos:7 /bin/sh -c "cd /srv/code && ./ci/papr-vmcheck.sh"

---

branches:
  - master
  - auto
  - try

# NB: when bumping 28 here, also bump fedora.repo, and compose script

context: f28-compose

build: false

timeout: 50m

required: true

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/28/atomic
  # Compose tests are slow and should be parallelized
  specs:
    cpus: 4

# Copy yum.repos.d to get any injected repos from the host, which
# will point to a closer mirror.  Note we substitute $releasever
# since https://github.com/projectatomic/rpm-ostree/pull/875
tests:
  - docker run --privileged --rm
    -e CONFIGOPTS=--enable-rust
    -e CI_PKGS=cargo
    -e RPMOSTREE_COMPOSE_TEST_USE_REPOS=/etc/yum.repos.d.host
    -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $(pwd):/srv/code -w /srv/code
    registry.fedoraproject.org/fedora:28 /bin/sh -c
    "./ci/build.sh && make install && ./tests/compose"

artifacts:
  - test-compose-logs

---

branches:
  - master
  - auto
  - try

context: f28-ex-container
build: false
timeout: 30m
required: false

# See the f28-compose context for why we do things this way.
host:
  distro: fedora/28/atomic

tests:
  - docker run --privileged --rm
    -e RPMOSTREE_COMPOSE_TEST_USE_REPOS=/etc/yum.repos.d.host
    -v /etc/yum.repos.d:/etc/yum.repos.d.host:ro
    -v $(pwd):/srv/code -w /srv/code
    registry.fedoraproject.org/fedora:28 /bin/sh -c
    "./ci/build.sh && make install && adduser unpriv && setfacl -m u:unpriv:rwX . && runuser -u unpriv ./tests/ex-container"

artifacts:
  - ex-container-logs
